-- Initialisation du serveur PostgreSQL de développement (ADR-0020).
--
-- ⚠ Joué UNE SEULE FOIS, à la CRÉATION du volume `pgsql-data`. Sur un volume qui
-- existe déjà, l'entrypoint de l'image ignore ce répertoire sans rien dire. Pour
-- l'appliquer à un environnement déjà monté :
--
--     docker compose exec postgres psql -U takussan -d takussan -f /docker-entrypoint-initdb.d/01-init.sql
--
-- ou, plus radical, `docker compose down -v` puis `up` — il n'y a aucune donnée à
-- perdre en développement, `php artisan migrate:fresh --seed` la reconstruit.

-- ─── Le seul droit que l'image ne donne pas, et pourquoi il est indispensable ───────
--
-- Le rôle `takussan` est créé par `POSTGRES_USER`. Ce script n'AJOUTE qu'une chose :
-- le droit de créer des bases.
--
-- La suite de tests crée UNE BASE PAR PROCESSUS (`Tests\Support\TestDatabase`). C'est
-- la CINQUIÈME ressource partagée par machine de ce dépôt, et la seule que la migration
-- vers PostgreSQL CRÉE au lieu de la révéler : sous SQLite `:memory:`, chaque processus
-- PHP avait sa base gratuitement, sans que personne ait eu à le décider. Sur PostgreSQL,
-- tous les processus de la machine parlent au même serveur — et sans base par processus,
-- le `migrate:fresh` de `RefreshDatabase` de l'un vide les tables sous l'autre, qui
-- rougit alors sur une assertion métier parfaitement juste.
--
-- C'est la panne D-44, à l'identique, sur une autre ressource.
--
-- `--parallel` en a besoin pour la même raison, un cran plus bas : ParaTest ouvre N
-- bases, une par worker.
--
-- ⚠ Ce droit est un droit de DÉVELOPPEMENT ET DE CI. Il ne doit PAS être accordé au
-- rôle applicatif de production : là-bas, personne ne crée de base à l'exécution.
ALTER ROLE takussan CREATEDB;

-- ─── Ce que ce script ne fait PAS, délibérément ─────────────────────────────────────
--
-- Il ne crée AUCUNE extension. Ni `vector`, ni `pg_trgm`, ni `citext`.
--
-- L'image est `pgvector/pgvector:pg17` pour que l'extension soit DISPONIBLE — c'est le
-- provisionnement qui se décide dans ce chantier, pas le schéma (ADR-0020 §2). Chaque
-- extension viendra avec le ticket qui en a besoin, et avec la migration qui l'installe :
-- une extension créée « au cas où » est une dépendance que personne n'a décidée.
--
-- Pour vérifier qu'elle est bien disponible sans l'installer :
--
--     SELECT name, default_version FROM pg_available_extensions WHERE name = 'vector';
