import type { PropertyDetail } from '@/types/property';

/** Un bien complet pour les tests du comparateur (`CompareCarousel`, `CompareClient`). */
export function makeProperty(overrides: Partial<PropertyDetail> = {}): PropertyDetail {
  return {
    id: 1,
    reference_number: 'TK-2026-ABC',
    title: 'Villa Almadies',
    slug: 'villa-almadies',
    price: 120_000_000,
    currency: 'XOF',
    type: 'villa',
    contract_type: 'sale',
    rent_period: null,
    status: 'available',
    visibility: 'public',
    bedrooms: 4,
    bathrooms: 3,
    area: 220,
    furnished: true,
    featured: false,
    main_photo_url: null,
    published_at: null,
    created_at: '2026-01-01T00:00:00.000Z',
    type_label: 'Villa',
    contract_type_label: 'Vente',
    rent_period_label: null,
    status_label: 'Disponible',
    title_type: null,
    title_type_label: null,
    condition_label: null,
    floor_number: null,
    total_floors: null,
    year_built: 2020,
    parking_spaces: 2,
    views_count: 0,
    favorites_count: 0,
    average_rating: null,
    reviews_count: 0,
    description: null,
    photos: [],
    media_extra: { videos: [], plans: [], virtual_tour_url: null },
    tags: [
      { id: 1, name: 'WiFi', slug: 'wifi', type: 'amenity', icon: null, color: null },
      { id: 2, name: 'Piscine', slug: 'piscine', type: 'amenity', icon: null, color: null },
    ],
    owner: {
      id: 1,
      name: 'Fatou',
      avatar_url: null,
      is_agent: true,
      member_since: null,
    },
    primary_contact: null,
    agency: null,
    documents: [],
    price_history: [],
    rejection_reason: null,
    submitted_at: null,
    approved_at: null,
    rejected_at: null,
    location: {
      full: 'Almadies, Dakar',
      street: null,
      quarter: 'Almadies',
      city: 'Dakar',
      region: null,
      country: null,
      postal_code: null,
      latitude: null,
      longitude: null,
    },
    ...overrides,
  };
}
