<?php

namespace App\Http\Controllers;

use App\Models\Enums\EmailFrequency;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

/**
 * TCK-103 — One-click unsubscribe from digest emails.
 *
 * The URL is signed (generated by URL::signedRoute) so no authentication
 * is required. Sets email_frequency=off for the given user.
 */
class NotificationUnsubscribeController extends Controller
{
    public function __invoke(Request $request, User $user): RedirectResponse
    {
        $user->update(['email_frequency' => EmailFrequency::Off]);

        return redirect(
            config('app.frontend_url', config('app.url')).'/app/profile/notifications?unsubscribed=1'
        );
    }
}
